version: '3.6'
services:
  db:
    container_name: unifi-controller-db
    image: mongo:3.6
    networks:
      - unifi
    restart: always
    volumes:
      - unifi-controller-db-config:/data/configdb
      - unifi-controller-db-data:/data/db
  controller:
    container_name: unifi-controller
    depends_on:
      - db
    environment:
      DB_NAME: unifi
      DB_URI: mongodb://db/unifi
      STATDB_URI: mongodb://db/unifi_stat
    image: jacobalberty/unifi:6.0.45
    init: true
    networks:
      - unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller communication.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    restart: always
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    user: unifi
    volumes:
      # Mount local folder for backups and autobackups
      - unifi-controller-backup:/unifi/data/backup
      - unifi-controller-cert:/unifi/cert
      - unifi-controller-data:/unifi/data
      - unifi-controller:/unifi
      - unifi-controller-init:/unifi/init.d
      - unifi-controller-log:/unifi/log
      - unifi-controller-run:/var/run/unifi
networks:
  unifi:
    name: unifi
volumes:
  unifi-controller-db-config:
    name: unifi-controller-db-config
  name: unifi-controller-db-data:
    name: unifi-controller-db-data
  unifi-controller-backup:
    name: unifi-controller-backup
  unifi-controller-cert:
    name: unifi-controller-cert
  unifi-controller-data:
    name: unifi-controller-data
  unifi-controller:
    name: unifi-controller
  unifi-controller-init:
    name: unifi-controller-init
  unifi-controller-log:
    name: unifi-controller-log
  unifi-controller-run:
    name: unifi-controller-run
